(eval-when-compile    (require 'color-theme))
(defun color-theme-tom ()
  "Color theme by Tomas Orti Martin EEM/TSW/D, created 2017-01-14."
  (interactive)
  (color-theme-install
   '(color-theme-tom
     ((background-color . "white")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "black")
      (mouse-color . "black"))
     (;;(ac-fuzzy-cursor-color . "red")
      (compilation-message-face . underline)
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "black")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (hl-line-face . hl-line)
      (ibuffer-deletion-face . error)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . warning)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (list-matching-lines-prefix-face . shadow)
      (org-goto-interface . outline)
      (tags-tag-face . default)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 143 :width normal :foundry "unknown" :family "Ubuntu Mono"))))
     (ac-candidate-face ((t (:foreground "black" :background "lightgray" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "unknown" :family "Ubuntu Mono" :height 143))))
     (ac-candidate-mouse-face ((t (:foreground "white" :background "blue"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-gtags-candidate-face ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightgray" :foreground "navy" :height 143))))
     (ac-gtags-selection-face ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :foreground "white" :background "navy" :height 143))))
     (ac-selection-face ((t (:foreground "white" :background "steelblue" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "unknown" :family "Ubuntu Mono" :height 143))))
     (ac-yasnippet-candidate-face ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "sandybrown" :foreground "black" :height 143))))
     (ac-yasnippet-selection-face ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :foreground "white" :background "coral3" :height 143))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-bookmark ((t (:bold t :weight bold))))
     (bookmark-menu-heading ((t (:foreground "ForestGreen"))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t :foreground "RoyalBlue3"))))
     (calendar-month-header ((t (:foreground "Blue1"))))
     (calendar-today ((t (:underline t))))
     (calendar-weekday-header ((t (:foreground "dark cyan"))))
     (calendar-weekend-header ((t (:foreground "Firebrick"))))
     (change-log-acknowledgment ((t (:foreground "Firebrick"))))
     (change-log-conditionals ((t (:foreground "sienna"))))
     (change-log-date ((t (:foreground "VioletRed4"))))
     (change-log-email ((t (:foreground "sienna"))))
     (change-log-file ((t (:foreground "Blue1"))))
     (change-log-function ((t (:foreground "sienna"))))
     (change-log-list ((t (:foreground "Purple"))))
     (change-log-name ((t (:foreground "dark cyan"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "medium blue"))))
     (company-echo ((t (nil))))
     (company-echo-common ((t (:background "firebrick4"))))
     (company-preview ((t (:background "light blue"))))
     (company-preview-common ((t (:foreground "darkred"))))
     (company-preview-search ((t (:foreground "darkred"))))
     (company-scrollbar-bg ((t (:background "wheat"))))
     (company-scrollbar-fg ((t (:background "darkred"))))
     (company-tooltip ((t (:background "cornsilk" :foreground "black"))))
     (company-tooltip-annotation ((t (:foreground "firebrick4"))))
     (company-tooltip-annotation-selection ((t (:foreground "firebrick4"))))
     (company-tooltip-common ((t (:foreground "darkred"))))
     (company-tooltip-common-selection ((t (:foreground "darkred"))))
     (company-tooltip-mouse ((t (:background "darkseagreen2"))))
     (company-tooltip-search ((t (:background "darkseagreen2"))))
     (company-tooltip-search-selection ((t (:background "darkseagreen2"))))
     (company-tooltip-selection ((t (:background "light blue"))))
     (compilation-column-number ((t (:foreground "VioletRed4"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Red1"))))
     (compilation-info ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (compilation-line-number ((t (:foreground "Purple"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:distant-foreground "gtk_selection_fg_color" :background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:distant-foreground "gtk_selection_fg_color" :background "dimgray" :foreground "white"))))
     (cursor ((t (:background "black"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "magenta4"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "blue1"))))
     (custom-group-subtitle ((t (:bold t :weight bold))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "blue1" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "red1" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "RoyalBlue3"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "dark green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "blue1" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "RoyalBlue3" :height 0.8))))
     (diary ((t (:foreground "red1"))))
     (diff-added ((t (:background "#ddffdd"))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-file-header ((t (:bold t :background "grey70" :weight bold))))
     (diff-function ((t (:background "grey80"))))
     (diff-header ((t (:background "grey80"))))
     (diff-hunk-header ((t (:background "grey80"))))
     (diff-index ((t (:bold t :weight bold :background "grey70"))))
     (diff-indicator-added ((t (:background "#ddffdd"))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (:background "#ffdddd"))))
     (diff-nonexistent ((t (:bold t :weight bold :background "grey70"))))
     (diff-refine-added ((t (:background "#aaffaa"))))
     (diff-refine-changed ((t (:background "#ffff55"))))
     (diff-refine-removed ((t (:background "#ffbbbb"))))
     (diff-removed ((t (:background "#ffdddd"))))
     (dired-directory ((t (:foreground "Blue1"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-header ((t (:foreground "ForestGreen"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "dark cyan"))))
     (dired-marked ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (dired-perm-write ((t (:foreground "Firebrick"))))
     (dired-symlink ((t (:foreground "Purple"))))
     (dired-warning ((t (:bold t :foreground "Red1" :weight bold))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (error ((t (:bold t :foreground "Red1" :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (ffap ((t (:background "darkseagreen2"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flycheck-error ((t (:underline (:style wave :color "Red1")))))
     (flycheck-error-list-checker-name ((t (:foreground "Blue1"))))
     (flycheck-error-list-column-number ((t (:foreground "dark cyan"))))
     (flycheck-error-list-error ((t (:bold t :weight bold :foreground "Red1"))))
     (flycheck-error-list-highlight ((t (:background "darkseagreen2"))))
     (flycheck-error-list-id ((t (:foreground "ForestGreen"))))
     (flycheck-error-list-info ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (flycheck-error-list-line-number ((t (:foreground "dark cyan"))))
     (flycheck-error-list-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (flycheck-fringe-error ((t (:bold t :weight bold :foreground "Red1"))))
     (flycheck-fringe-info ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (flycheck-fringe-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (flycheck-info ((t (:underline (:style wave :color "ForestGreen")))))
     (flycheck-warning ((t (:underline (:style wave :color "DarkOrange")))))
     (flymake-errline ((t (:underline (:style wave :color "Red1")))))
     (flymake-warnline ((t (:underline (:style wave :color "DarkOrange")))))
     (font-lock-builtin-face ((t (:foreground "dark slate blue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "Firebrick"))))
     (font-lock-comment-face ((t (:foreground "Firebrick"))))
     (font-lock-constant-face ((t (:foreground "dark cyan"))))
     (font-lock-doc-face ((t (:foreground "VioletRed4"))))
     (font-lock-function-name-face ((t (:foreground "Blue1"))))
     (font-lock-keyword-face ((t (:foreground "Purple"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "dark slate blue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "VioletRed4"))))
     (font-lock-type-face ((t (:foreground "ForestGreen"))))
     (font-lock-variable-name-face ((t (:foreground "sienna"))))
     (font-lock-warning-face ((t (:bold t :weight bold :foreground "Red1"))))
     (fringe ((t (:background "#d0f0ff"))))
     (git-commit-comment-action ((t (:foreground "sienna"))))
     (git-commit-comment-branch ((t (:foreground "sienna"))))
     (git-commit-comment-detached ((t (:foreground "sienna"))))
     (git-commit-comment-file ((t (:foreground "VioletRed4"))))
     (git-commit-comment-heading ((t (:foreground "Purple"))))
     (git-commit-known-pseudo-header ((t (:foreground "Purple"))))
     (git-commit-nonempty-second-line ((t (:bold t :foreground "Red1" :weight bold))))
     (git-commit-note ((t (:foreground "VioletRed4"))))
     (git-commit-overlong-summary ((t (:bold t :foreground "Red1" :weight bold))))
     (git-commit-pseudo-header ((t (:foreground "VioletRed4"))))
     (git-commit-summary ((t (:foreground "ForestGreen"))))
     (glyphless-char ((t (:height 0.6))))
     (hc-hard-space ((t (:background "Aquamarine"))))
     (hc-other-char ((t (:background "HotPink"))))
     (hc-tab ((t (:background "wheat"))))
     (hc-trailing-whitespace ((t (:background "Gold"))))
     (hdefd-functions ((t (:foreground "#00006DE06DE0"))))
     (hdefd-undefined ((t (:foreground "Orange"))))
     (hdefd-variables ((t (:foreground "Orchid"))))
     (header-line ((t (:inverse-video nil :background "grey90" :foreground "grey20" :box nil))))
     (helm-M-x-key ((t (:foreground "orange" :underline t))))
     (helm-action ((t (:underline t))))
     (helm-bookmark-addressbook ((t (:foreground "tomato"))))
     (helm-bookmark-directory ((t (:foreground "DarkRed" :background "LightGray"))))
     (helm-bookmark-file ((t (:foreground "Deepskyblue2"))))
     (helm-bookmark-gnus ((t (:foreground "magenta"))))
     (helm-bookmark-info ((t (:foreground "green"))))
     (helm-bookmark-man ((t (:foreground "Orange4"))))
     (helm-bookmark-w3m ((t (:foreground "yellow"))))
     (helm-buffer-directory ((t (:background "LightGray" :foreground "DarkRed"))))
     (helm-buffer-file ((t (:foreground "dark slate blue"))))
     (helm-buffer-not-saved ((t (:foreground "Indianred2"))))
     (helm-buffer-process ((t (:foreground "Sienna3"))))
     (helm-buffer-saved-out ((t (:background "black" :foreground "red"))))
     (helm-buffer-size ((t (:foreground "SlateGray"))))
     (helm-candidate-number ((t (:background "#faffb5" :foreground "black"))))
     (helm-etags-file ((t (:foreground "Lightgoldenrod4" :underline t))))
     (helm-ff-directory ((t (:background "LightGray" :foreground "DarkRed"))))
     (helm-ff-dirs ((t (:foreground "Blue1"))))
     (helm-ff-dotted-directory ((t (:background "DimGray" :foreground "black"))))
     (helm-ff-dotted-symlink-directory ((t (:background "DimGray" :foreground "DarkOrange"))))
     (helm-ff-executable ((t (:foreground "green"))))
     (helm-ff-file ((t (:foreground "dark slate blue"))))
     (helm-ff-invalid-symlink ((t (:background "red" :foreground "black"))))
     (helm-ff-prefix ((t (:background "yellow" :foreground "black"))))
     (helm-ff-symlink ((t (:foreground "DarkOrange"))))
     (helm-grep-cmd-line ((t (:background "#ddffdd"))))
     (helm-grep-file ((t (:foreground "BlueViolet" :underline t))))
     (helm-grep-finish ((t (:foreground "Green"))))
     (helm-grep-lineno ((t (:foreground "Darkorange1"))))
     (helm-grep-match ((t (:foreground "#b00000"))))
     (helm-header ((t (:box nil :foreground "grey20" :background "grey90" :inverse-video nil))))
     (helm-header-line-left-margin ((t (:background "yellow" :foreground "black"))))
     (helm-helper ((t (:inverse-video nil :background "grey90" :foreground "grey20" :box nil))))
     (helm-history-deleted ((t (:foreground "black" :background "red"))))
     (helm-history-remote ((t (:foreground "Indianred1"))))
     (helm-lisp-completion-info ((t (:foreground "red"))))
     (helm-lisp-show-completion ((t (:background "DarkSlateGray"))))
     (helm-locate-finish ((t (:foreground "Green"))))
     (helm-match ((t (:foreground "#b00000"))))
     (helm-match-item ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (helm-moccur-buffer ((t (:foreground "DarkTurquoise" :underline t))))
     (helm-prefarg ((t (:foreground "red"))))
     (helm-resume-need-update ((t (:background "red"))))
     (helm-selection ((t (:background "#b5ffd1" :distant-foreground "black"))))
     (helm-selection-line ((t (:background "darkseagreen2" :distant-foreground "black"))))
     (helm-separator ((t (:foreground "#ffbfb5"))))
     (helm-source-header ((t (:bold t :background "#abd7f0" :foreground "black" :weight bold :height 1.3 :family "Sans Serif"))))
     (helm-visible-mark ((t (:background "#d1f5ea"))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkseagreen2"))))
     (highlight-indentation-current-column-face ((t (:background "black"))))
     (highlight-indentation-face ((t (:background "#d0f0ff"))))
     (hl-line ((t (:background "#FBFFAB"))))
     (holiday ((t (:background "pink"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Red1" :weight bold))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-virtual ((t (:foreground "dark slate blue"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "brown"))))
     (info-header-xref ((t (:foreground "RoyalBlue3" :underline t))))
     (info-index-match ((t (:background "yellow1"))))
     (info-menu-header ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
     (info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
     (info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-xref ((t (:underline t :foreground "RoyalBlue3"))))
     (info-xref-visited ((t (:foreground "magenta4" :underline t))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "RoyalBlue3" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (linum ((t (:foreground "grey50"))))
     (log-edit-header ((t (:foreground "Purple"))))
     (log-edit-summary ((t (:foreground "Blue1"))))
     (log-edit-unknown-header ((t (:foreground "Firebrick"))))
     (magit-bisect-bad ((t (:foreground "IndianRed4"))))
     (magit-bisect-good ((t (:foreground "DarkOliveGreen"))))
     (magit-bisect-skip ((t (:foreground "DarkGoldenrod"))))
     (magit-blame-date ((t (:foreground "black" :background "grey80"))))
     (magit-blame-hash ((t (:foreground "black" :background "grey80"))))
     (magit-blame-heading ((t (:background "grey80" :foreground "black"))))
     (magit-blame-name ((t (:foreground "black" :background "grey80"))))
     (magit-blame-summary ((t (:foreground "black" :background "grey80"))))
     (magit-branch-current ((t (:foreground "SkyBlue4" :box 1))))
     (magit-branch-local ((t (:foreground "SkyBlue4"))))
     (magit-branch-remote ((t (:foreground "DarkOliveGreen4"))))
     (magit-cherry-equivalent ((t (:foreground "magenta"))))
     (magit-cherry-unmatched ((t (:foreground "cyan"))))
     (magit-diff-added ((t (:background "#ddffdd" :foreground "#22aa22"))))
     (magit-diff-added-highlight ((t (:background "#cceecc" :foreground "#22aa22"))))
     (magit-diff-base ((t (:background "#ffffcc" :foreground "#aaaa11"))))
     (magit-diff-base-highlight ((t (:background "#eeeebb" :foreground "#aaaa11"))))
     (magit-diff-conflict-heading ((t (:foreground "grey30" :background "grey80"))))
     (magit-diff-context ((t (:foreground "grey50"))))
     (magit-diff-context-highlight ((t (:background "grey95" :foreground "grey50"))))
     (magit-diff-file-heading ((t (:bold t :weight bold))))
     (magit-diff-file-heading-highlight ((t (:bold t :weight bold))))
     (magit-diff-file-heading-selection ((t (:bold t :weight bold :foreground "salmon4"))))
     (magit-diff-hunk-heading ((t (:background "grey80" :foreground "grey30"))))
     (magit-diff-hunk-heading-highlight ((t (:background "grey75" :foreground "grey30"))))
     (magit-diff-hunk-heading-selection ((t (:background "grey75" :foreground "salmon4"))))
     (magit-diff-hunk-region ((t (:bold t :weight bold))))
     (magit-diff-lines-boundary ((t (:background "LightSalmon3" :foreground "grey30"))))
     (magit-diff-lines-heading ((t (:foreground "grey30" :background "LightSalmon3"))))
     (magit-diff-our ((t (:foreground "#aa2222" :background "#ffdddd"))))
     (magit-diff-our-highlight ((t (:foreground "#aa2222" :background "#eecccc"))))
     (magit-diff-removed ((t (:background "#ffdddd" :foreground "#aa2222"))))
     (magit-diff-removed-highlight ((t (:background "#eecccc" :foreground "#aa2222"))))
     (magit-diff-their ((t (:foreground "#22aa22" :background "#ddffdd"))))
     (magit-diff-their-highlight ((t (:foreground "#22aa22" :background "#cceecc"))))
     (magit-diff-whitespace-warning ((t (:background "red1"))))
     (magit-diffstat-added ((t (:foreground "#22aa22"))))
     (magit-diffstat-removed ((t (:foreground "#aa2222"))))
     (magit-dimmed ((t (:foreground "grey50"))))
     (magit-filename ((t (:weight normal))))
     (magit-hash ((t (:foreground "grey60"))))
     (magit-head ((t (:foreground "SkyBlue4"))))
     (magit-header-line ((t (:bold t :weight bold :foreground "DarkGoldenrod4"))))
     (magit-log-author ((t (:foreground "firebrick"))))
     (magit-log-date ((t (:foreground "grey30"))))
     (magit-log-graph ((t (:foreground "grey30"))))
     (magit-popup-argument ((t (:bold t :foreground "Red1" :weight bold))))
     (magit-popup-disabled-argument ((t (:foreground "grey50"))))
     (magit-popup-heading ((t (:foreground "Purple"))))
     (magit-popup-key ((t (:foreground "dark slate blue"))))
     (magit-popup-option-value ((t (:foreground "VioletRed4"))))
     (magit-process-ng ((t (:bold t :weight bold :foreground "red"))))
     (magit-process-ok ((t (:bold t :weight bold :foreground "green"))))
     (magit-reflog-amend ((t (:foreground "magenta"))))
     (magit-reflog-checkout ((t (:foreground "blue"))))
     (magit-reflog-cherry-pick ((t (:foreground "green"))))
     (magit-reflog-commit ((t (:foreground "green"))))
     (magit-reflog-merge ((t (:foreground "green"))))
     (magit-reflog-other ((t (:foreground "cyan"))))
     (magit-reflog-rebase ((t (:foreground "magenta"))))
     (magit-reflog-remote ((t (:foreground "cyan"))))
     (magit-reflog-reset ((t (:foreground "red"))))
     (magit-refname ((t (:foreground "grey30"))))
     (magit-refname-stash ((t (:foreground "grey30"))))
     (magit-refname-wip ((t (:foreground "grey30"))))
     (magit-section-heading ((t (:bold t :foreground "DarkGoldenrod4" :weight bold))))
     (magit-section-heading-selection ((t (:foreground "salmon4"))))
     (magit-section-highlight ((t (:background "grey95"))))
     (magit-section-secondary-heading ((t (:bold t :weight bold))))
     (magit-sequence-done ((t (:foreground "grey60"))))
     (magit-sequence-drop ((t (:foreground "IndianRed"))))
     (magit-sequence-head ((t (:foreground "SkyBlue4"))))
     (magit-sequence-onto ((t (:foreground "grey60"))))
     (magit-sequence-part ((t (:foreground "Goldenrod4"))))
     (magit-sequence-pick ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 143))))
     (magit-sequence-stop ((t (:foreground "DarkOliveGreen4"))))
     (magit-signature-bad ((t (:foreground "red"))))
     (magit-signature-good ((t (:foreground "green"))))
     (magit-signature-untrusted ((t (:foreground "cyan"))))
     (magit-tag ((t (:foreground "Goldenrod4"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (message-cited-text ((t (:foreground "red"))))
     (message-header-cc ((t (:foreground "MidnightBlue"))))
     (message-header-name ((t (:foreground "cornflower blue"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "blue4" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "steel blue"))))
     (message-header-subject ((t (:bold t :foreground "navy blue" :weight bold))))
     (message-header-to ((t (:bold t :foreground "MidnightBlue" :weight bold))))
     (message-header-xheader ((t (:foreground "blue"))))
     (message-mml ((t (:foreground "ForestGreen"))))
     (message-separator ((t (:foreground "brown"))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mm-command-output ((t (:foreground "red3"))))
     (mode-line ((t (:background "grey85" :foreground "black" :inverse-video nil))))
     (mode-line-buffer-id ((t (:bold t :weight bold :foreground "Blue" :inverse-video nil))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#fdf6e3" :foreground "grey20" :inverse-video nil))))
     (mouse ((t (nil))))
     (next-error ((t (:distant-foreground "gtk_selection_fg_color" :background "gtk_selection_bg_color"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "sienna"))))
     (nxml-attribute-prefix ((t (:foreground "dark slate blue"))))
     (nxml-attribute-value ((t (:foreground "VioletRed4"))))
     (nxml-attribute-value-delimiter ((t (:foreground "VioletRed4"))))
     (nxml-cdata-section-CDATA ((t (:foreground "dark slate blue"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "dark cyan"))))
     (nxml-char-ref-number ((t (:foreground "dark cyan"))))
     (nxml-comment-content ((t (:foreground "Firebrick"))))
     (nxml-comment-delimiter ((t (:foreground "Firebrick"))))
     (nxml-delimited-data ((t (:foreground "VioletRed4"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "Blue1"))))
     (nxml-element-prefix ((t (:foreground "dark slate blue"))))
     (nxml-entity-ref-delimiter ((t (:foreground "dark cyan"))))
     (nxml-entity-ref-name ((t (:foreground "dark cyan"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal :foundry "misc" :family "fixed"))))
     (nxml-hash ((t (:foreground "dark slate blue"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "dark slate blue"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "sienna"))))
     (nxml-namespace-attribute-value ((t (:foreground "VioletRed4"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "VioletRed4"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "dark slate blue"))))
     (nxml-outline-active-indicator ((t (:box 1))))
     (nxml-outline-ellipsis ((t (:bold t :weight bold))))
     (nxml-outline-indicator ((t (nil))))
     (nxml-processing-instruction-content ((t (:foreground "VioletRed4"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:foreground "Purple"))))
     (nxml-prolog-keyword ((t (:foreground "Purple"))))
     (nxml-prolog-literal-content ((t (:foreground "VioletRed4"))))
     (nxml-prolog-literal-delimiter ((t (:foreground "VioletRed4"))))
     (nxml-ref ((t (:foreground "dark cyan"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (org-agenda-calendar-event ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 143))))
     (org-agenda-calendar-sexp ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 143))))
     (org-agenda-clocking ((t (:background "yellow1"))))
     (org-agenda-column-dateline ((t (:weight normal :slant normal :underline nil :strike-through nil :background "grey90"))))
     (org-agenda-current-time ((t (:foreground "DarkGoldenrod"))))
     (org-agenda-date ((t (:foreground "Blue1"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "Blue1" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "Blue1" :weight bold))))
     (org-agenda-diary ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 143))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "ForestGreen"))))
     (org-agenda-filter-category ((t (:inverse-video nil :foreground "black" :background "grey85"))))
     (org-agenda-filter-regexp ((t (:inverse-video nil :foreground "black" :background "grey85"))))
     (org-agenda-filter-tags ((t (:inverse-video nil :foreground "black" :background "grey85"))))
     (org-agenda-restriction-lock ((t (:background "#eeeeee"))))
     (org-agenda-structure ((t (:foreground "Blue1"))))
     (org-archived ((t (:foreground "grey50"))))
     (org-block ((t (:foreground "grey50"))))
     (org-block-begin-line ((t (:foreground "Firebrick"))))
     (org-block-end-line ((t (:foreground "Firebrick"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Red1"))))
     (org-clock-overlay ((t (:background "LightGray" :foreground "black"))))
     (org-code ((t (:foreground "grey50"))))
     (org-column ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal))))
     (org-column-title ((t (:bold t :background "grey90" :underline t :weight bold))))
     (org-date ((t (:foreground "Purple" :underline t))))
     (org-date-selected ((t (:background "Red1"))))
     (org-default ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 143))))
     (org-document-info ((t (:foreground "midnight blue"))))
     (org-document-info-keyword ((t (:foreground "grey50"))))
     (org-document-title ((t (:bold t :foreground "midnight blue" :weight bold))))
     (org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-drawer ((t (:foreground "Blue1"))))
     (org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Purple" :underline t))))
     (org-formula ((t (:foreground "Firebrick"))))
     (org-headline-done ((t (:foreground "RosyBrown"))))
     (org-hide ((t (:foreground "white"))))
     (org-latex-and-related ((t (:foreground "SaddleBrown"))))
     (org-level-1 ((t (:foreground "Blue1"))))
     (org-level-2 ((t (:foreground "sienna"))))
     (org-level-3 ((t (:foreground "Purple"))))
     (org-level-4 ((t (:foreground "Firebrick"))))
     (org-level-5 ((t (:foreground "ForestGreen"))))
     (org-level-6 ((t (:foreground "dark cyan"))))
     (org-level-7 ((t (:foreground "dark slate blue"))))
     (org-level-8 ((t (:foreground "VioletRed4"))))
     (org-link ((t (:underline t :foreground "RoyalBlue3"))))
     (org-list-dt ((t (:bold t :weight bold))))
     (org-macro ((t (:foreground "SaddleBrown"))))
     (org-meta-line ((t (:foreground "Firebrick"))))
     (org-mode-line-clock ((t (:inverse-video nil :foreground "black" :background "grey85"))))
     (org-mode-line-clock-overrun ((t (:inverse-video nil :foreground "black" :background "red"))))
     (org-priority ((t (:foreground "black" :background "aquamarine1" :box (:line-width 2 :color "orange" :style released-button)))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey50"))))
     (org-scheduled ((t (:foreground "DarkGreen"))))
     (org-scheduled-previously ((t (:foreground "Firebrick"))))
     (org-scheduled-today ((t (:foreground "DarkGreen"))))
     (org-sexp-date ((t (:foreground "Purple"))))
     (org-special-keyword ((t (:foreground "Purple"))))
     (org-table ((t (:foreground "Blue1"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-tag-group ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "DarkGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Red1" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "Firebrick"))))
     (org-verbatim ((t (:foreground "grey50"))))
     (org-verse ((t (:foreground "grey50"))))
     (org-warning ((t (:bold t :foreground "Red1" :weight bold))))
     (outline-1 ((t (:foreground "Blue1"))))
     (outline-2 ((t (:foreground "sienna"))))
     (outline-3 ((t (:foreground "Purple"))))
     (outline-4 ((t (:foreground "Firebrick"))))
     (outline-5 ((t (:foreground "ForestGreen"))))
     (outline-6 ((t (:foreground "dark cyan"))))
     (outline-7 ((t (:foreground "dark slate blue"))))
     (outline-8 ((t (:foreground "VioletRed4"))))
     (popup-face ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightgray" :foreground "black" :height 143))))
     (popup-isearch-match ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :stipple nil :background "sky blue" :height 143))))
     (popup-menu-face ((t (:foreground "black" :background "lightgray" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "unknown" :family "Ubuntu Mono" :height 143))))
     (popup-menu-mouse-face ((t (:background "blue" :foreground "white"))))
     (popup-menu-selection-face ((t (:family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "steelblue" :foreground "white" :height 143))))
     (popup-menu-summary-face ((t (:foreground "dimgray" :family "Ubuntu Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightgray" :height 143))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-summary-face ((t (:background "lightgray" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "unknown" :family "Ubuntu Mono" :foreground "dimgray" :height 143))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (region ((t (:background "gtk_selection_bg_color" :distant-foreground "gtk_selection_fg_color"))))
     (rng-error ((t (:bold t :foreground "Red1" :weight bold))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "yellow1"))))
     (sgml-namespace ((t (:foreground "dark slate blue"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (smerge-base ((t (:background "#ffffaa"))))
     (smerge-markers ((t (:background "grey85"))))
     (smerge-mine ((t (:background "#ffdddd"))))
     (smerge-other ((t (:background "#ddffdd"))))
     (smerge-refined-added ((t (:background "#aaffaa"))))
     (smerge-refined-changed ((t (nil))))
     (smerge-refined-removed ((t (:background "#ffbbbb"))))
     (sml/charging ((t (:inverse-video nil :foreground "ForestGreen"))))
     (sml/client ((t (:bold t :weight bold :foreground "#5b2507" :inverse-video nil))))
     (sml/col-number ((t (:inverse-video nil :foreground "gray20"))))
     (sml/discharging ((t (:inverse-video nil :foreground "Red"))))
     (sml/filename ((t (:bold t :inverse-video nil :foreground "Blue" :weight bold))))
     (sml/folder ((t (:inverse-video nil :foreground "gray20" :weight normal))))
     (sml/git ((t (:bold t :weight bold :foreground "DarkGreen" :inverse-video nil))))
     (sml/global ((t (:foreground "gray20" :inverse-video nil))))
     (sml/line-number ((t (:bold t :foreground "dark violet" :inverse-video nil :weight bold))))
     (sml/minor-modes ((t (:inverse-video nil :foreground "gray20"))))
     (sml/modes ((t (:bold t :inverse-video nil :foreground "dark violet" :weight bold))))
     (sml/modified ((t (:bold t :inverse-video nil :foreground "Red" :weight bold))))
     (sml/mule-info ((t (:inverse-video nil :foreground "gray20"))))
     (sml/name-filling ((t (:weight normal :inverse-video nil :foreground "#5b2507"))))
     (sml/not-modified ((t (:inverse-video nil :foreground "gray20"))))
     (sml/numbers-separator ((t (:foreground "gray20" :inverse-video nil))))
     (sml/outside-modified ((t (:inverse-video nil :background "#c82829" :foreground "#ffffff"))))
     (sml/position-percentage ((t (:foreground "#5b2507" :inverse-video nil :weight normal))))
     (sml/prefix ((t (:bold t :inverse-video nil :foreground "#5b2507" :weight bold))))
     (sml/process ((t (:bold t :weight bold :foreground "#5b2507" :inverse-video nil))))
     (sml/read-only ((t (:bold t :inverse-video nil :foreground "DarkGreen" :weight bold))))
     (sml/remote ((t (:inverse-video nil :foreground "gray20"))))
     (sml/sudo ((t (:foreground "#ffffff" :background "#c82829" :inverse-video nil))))
     (sml/time ((t (:bold t :weight bold :foreground "dark violet" :inverse-video nil))))
     (sml/vc ((t (:bold t :inverse-video nil :foreground "DarkGreen" :weight bold))))
     (sml/vc-edited ((t (:bold t :weight bold :foreground "#5b2507" :inverse-video nil))))
     (success ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (tty-menu-disabled-face ((t (:background "blue" :foreground "lightgray"))))
     (tty-menu-enabled-face ((t (:bold t :background "blue" :foreground "yellow" :weight bold))))
     (tty-menu-selected-face ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (window-divider ((t (:foreground "gray60"))))
     (window-divider-first-pixel ((t (:foreground "gray80"))))
     (window-divider-last-pixel ((t (:foreground "gray40"))))
     (yas--field-debug-face ((t (nil))))
     (yas-field-highlight-face ((t (:distant-foreground "gtk_selection_fg_color" :background "gtk_selection_bg_color")))))))
(add-to-list 'color-themes '(color-theme-tom  "Tom" "Tomas Orti"))
