(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by Tomas Orti Martin EEM/TSW/D, created 2017-04-26."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "white")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "black")
      (mouse-color . "black"))
     ((compilation-message-face . underline)
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "black")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (hl-line-face . hl-line)
      (ibuffer-deletion-face . error)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . warning)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (list-matching-lines-prefix-face . shadow)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 143 :width normal :foundry "unknown" :family "Ubuntu Mono"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t :foreground "RoyalBlue3"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "medium blue"))))
     (compilation-column-number ((t (:foreground "VioletRed4"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Red1"))))
     (compilation-info ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (compilation-line-number ((t (:foreground "Purple"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:distant-foreground "gtk_selection_fg_color" :background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:distant-foreground "gtk_selection_fg_color" :background "dimgray" :foreground "white"))))
     (cursor ((t (:background "black"))))
     (dired-directory ((t (:foreground "Blue1"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-header ((t (:foreground "ForestGreen"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "dark cyan"))))
     (dired-marked ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (dired-perm-write ((t (:foreground "Firebrick"))))
     (dired-symlink ((t (:foreground "Purple"))))
     (dired-warning ((t (:bold t :foreground "Red1" :weight bold))))
     (error ((t (:bold t :foreground "Red1" :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (font-lock-builtin-face ((t (:foreground "dark slate blue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "Firebrick"))))
     (font-lock-comment-face ((t (:foreground "Firebrick"))))
     (font-lock-constant-face ((t (:foreground "dark cyan"))))
     (font-lock-doc-face ((t (:foreground "VioletRed4"))))
     (font-lock-function-name-face ((t (:foreground "Blue1"))))
     (font-lock-keyword-face ((t (:foreground "Purple"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "dark slate blue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "VioletRed4"))))
     (font-lock-type-face ((t (:foreground "ForestGreen"))))
     (font-lock-variable-name-face ((t (:foreground "sienna"))))
     (font-lock-warning-face ((t (:bold t :weight bold :foreground "Red1"))))
     (fringe ((t (:background "#d0f0ff"))))
     (glyphless-char ((t (:height 0.6))))
     (hc-hard-space ((t (:background "Aquamarine"))))
     (hc-other-char ((t (:background "HotPink"))))
     (hc-tab ((t (:background "LemonChiffon"))))
     (hc-trailing-whitespace ((t (:background "Gold"))))
     (header-line ((t (:inverse-video nil :background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkseagreen2"))))
     (hl-line ((t (:background "#FBFFAB"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "brown"))))
     (info-header-xref ((t (:foreground "RoyalBlue3" :underline t))))
     (info-index-match ((t (:background "yellow1"))))
     (info-menu-header ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
     (info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
     (info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-xref ((t (:underline t :foreground "RoyalBlue3"))))
     (info-xref-visited ((t (:foreground "magenta4" :underline t))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "RoyalBlue3" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (linum ((t (:foreground "grey50"))))
     (makefile-makepp-perl ((t (:background "LightBlue1"))))
     (makefile-shell ((t (nil))))
     (makefile-space ((t (:background "hotpink"))))
     (makefile-targets ((t (:foreground "Blue1"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mode-line ((t (:background "grey85" :foreground "black" :inverse-video nil))))
     (mode-line-buffer-id ((t (:bold t :weight bold :foreground "Blue" :inverse-video nil))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#fdf6e3" :foreground "grey20" :inverse-video nil))))
     (mouse ((t (nil))))
     (next-error ((t (:distant-foreground "gtk_selection_fg_color" :background "gtk_selection_bg_color"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (region ((t (:background "gtk_selection_bg_color" :distant-foreground "gtk_selection_fg_color"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "yellow1"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (sml/charging ((t (:inverse-video nil :foreground "ForestGreen"))))
     (sml/client ((t (:bold t :weight bold :foreground "#5b2507" :inverse-video nil))))
     (sml/col-number ((t (:inverse-video nil :foreground "gray20"))))
     (sml/discharging ((t (:inverse-video nil :foreground "Red"))))
     (sml/filename ((t (:bold t :inverse-video nil :foreground "Blue" :weight bold))))
     (sml/folder ((t (:inverse-video nil :foreground "gray20" :weight normal))))
     (sml/git ((t (:bold t :weight bold :foreground "DarkGreen" :inverse-video nil))))
     (sml/global ((t (:foreground "gray20" :inverse-video nil))))
     (sml/line-number ((t (:bold t :foreground "Black" :inverse-video nil :weight bold))))
     (sml/minor-modes ((t (:inverse-video nil :foreground "gray20"))))
     (sml/modes ((t (:inverse-video nil :foreground "Black"))))
     (sml/modified ((t (:bold t :inverse-video nil :foreground "Red" :weight bold))))
     (sml/mule-info ((t (:inverse-video nil :foreground "gray20"))))
     (sml/name-filling ((t (:weight normal :inverse-video nil :foreground "#5b2507"))))
     (sml/not-modified ((t (:inverse-video nil :foreground "gray20"))))
     (sml/numbers-separator ((t (:foreground "gray20" :inverse-video nil))))
     (sml/outside-modified ((t (:inverse-video nil :background "#c82829" :foreground "#ffffff"))))
     (sml/position-percentage ((t (:foreground "#5b2507" :inverse-video nil :weight normal))))
     (sml/prefix ((t (:bold t :inverse-video nil :foreground "#5b2507" :weight bold))))
     (sml/process ((t (:bold t :weight bold :foreground "#5b2507" :inverse-video nil))))
     (sml/read-only ((t (:bold t :inverse-video nil :foreground "DarkGreen" :weight bold))))
     (sml/remote ((t (:inverse-video nil :foreground "gray20"))))
     (sml/sudo ((t (:foreground "#ffffff" :background "#c82829" :inverse-video nil))))
     (sml/time ((t (:foreground "Black" :inverse-video nil))))
     (sml/vc ((t (:bold t :inverse-video nil :foreground "DarkGreen" :weight bold))))
     (sml/vc-edited ((t (:bold t :weight bold :foreground "#5b2507" :inverse-video nil))))
     (success ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (tty-menu-disabled-face ((t (:background "blue" :foreground "lightgray"))))
     (tty-menu-enabled-face ((t (:bold t :background "blue" :foreground "yellow" :weight bold))))
     (tty-menu-selected-face ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (window-divider ((t (:foreground "gray60"))))
     (window-divider-first-pixel ((t (:foreground "gray80"))))
     (window-divider-last-pixel ((t (:foreground "gray40")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))
